---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Get system architecture
  command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename
  changed_when: false

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    filename: docker
    state: present

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes
