---
- name: Install terraform
  hosts: all
  become: yes
  tasks:
    - name: Check if Terraform is already installed
      ansible.builtin.command: terraform --version
      register: terraform_check
      failed_when: false
      changed_when: false

    - name: Download HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: "0644"
      when: terraform_check.rc != 0

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp
      when: terraform_check.rc != 0

    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: yes
      when: terraform_check.rc != 0
